# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/danielsinclair/vscode/escli.refac7

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/danielsinclair/vscode/escli.refac7/vehicle-sim

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"gmock\" \"gtest\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/danielsinclair/vscode/escli.refac7/vehicle-sim/CMakeFiles /Users/danielsinclair/vscode/escli.refac7/vehicle-sim//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/danielsinclair/vscode/escli.refac7/vehicle-sim/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named engine-sim-cli

# Build rule for target.
engine-sim-cli: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 engine-sim-cli
.PHONY : engine-sim-cli

# fast build rule for target.
engine-sim-cli/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/build
.PHONY : engine-sim-cli/fast

#=============================================================================
# Target rules for targets named run_tests

# Build rule for target.
run_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_tests
.PHONY : run_tests

# fast build rule for target.
run_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/build
.PHONY : run_tests/fast

#=============================================================================
# Target rules for targets named engine-sim-bridge

# Build rule for target.
engine-sim-bridge: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 engine-sim-bridge
.PHONY : engine-sim-bridge

# fast build rule for target.
engine-sim-bridge/fast:
	$(MAKE) $(MAKESILENT) -f engine-sim-bridge/CMakeFiles/engine-sim-bridge.dir/build.make engine-sim-bridge/CMakeFiles/engine-sim-bridge.dir/build
.PHONY : engine-sim-bridge/fast

#=============================================================================
# Target rules for targets named copy-engine-sim-bridge

# Build rule for target.
copy-engine-sim-bridge: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 copy-engine-sim-bridge
.PHONY : copy-engine-sim-bridge

# fast build rule for target.
copy-engine-sim-bridge/fast:
	$(MAKE) $(MAKESILENT) -f engine-sim-bridge/CMakeFiles/copy-engine-sim-bridge.dir/build.make engine-sim-bridge/CMakeFiles/copy-engine-sim-bridge.dir/build
.PHONY : copy-engine-sim-bridge/fast

#=============================================================================
# Target rules for targets named bridge_unit_tests

# Build rule for target.
bridge_unit_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bridge_unit_tests
.PHONY : bridge_unit_tests

# fast build rule for target.
bridge_unit_tests/fast:
	$(MAKE) $(MAKESILENT) -f engine-sim-bridge/CMakeFiles/bridge_unit_tests.dir/build.make engine-sim-bridge/CMakeFiles/bridge_unit_tests.dir/build
.PHONY : bridge_unit_tests/fast

#=============================================================================
# Target rules for targets named engine-sim

# Build rule for target.
engine-sim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 engine-sim
.PHONY : engine-sim

# fast build rule for target.
engine-sim/fast:
	$(MAKE) $(MAKESILENT) -f engine-sim/CMakeFiles/engine-sim.dir/build.make engine-sim/CMakeFiles/engine-sim.dir/build
.PHONY : engine-sim/fast

#=============================================================================
# Target rules for targets named engine-sim-script-interpreter

# Build rule for target.
engine-sim-script-interpreter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 engine-sim-script-interpreter
.PHONY : engine-sim-script-interpreter

# fast build rule for target.
engine-sim-script-interpreter/fast:
	$(MAKE) $(MAKESILENT) -f engine-sim/CMakeFiles/engine-sim-script-interpreter.dir/build.make engine-sim/CMakeFiles/engine-sim-script-interpreter.dir/build
.PHONY : engine-sim-script-interpreter/fast

#=============================================================================
# Target rules for targets named engine-sim-app

# Build rule for target.
engine-sim-app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 engine-sim-app
.PHONY : engine-sim-app

# fast build rule for target.
engine-sim-app/fast:
	$(MAKE) $(MAKESILENT) -f engine-sim/CMakeFiles/engine-sim-app.dir/build.make engine-sim/CMakeFiles/engine-sim-app.dir/build
.PHONY : engine-sim-app/fast

#=============================================================================
# Target rules for targets named engine-sim-test

# Build rule for target.
engine-sim-test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 engine-sim-test
.PHONY : engine-sim-test

# fast build rule for target.
engine-sim-test/fast:
	$(MAKE) $(MAKESILENT) -f engine-sim/CMakeFiles/engine-sim-test.dir/build.make engine-sim/CMakeFiles/engine-sim-test.dir/build
.PHONY : engine-sim-test/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named simple-2d-constraint-solver

# Build rule for target.
simple-2d-constraint-solver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simple-2d-constraint-solver
.PHONY : simple-2d-constraint-solver

# fast build rule for target.
simple-2d-constraint-solver/fast:
	$(MAKE) $(MAKESILENT) -f engine-sim/dependencies/submodules/simple-2d-constraint-solver/CMakeFiles/simple-2d-constraint-solver.dir/build.make engine-sim/dependencies/submodules/simple-2d-constraint-solver/CMakeFiles/simple-2d-constraint-solver.dir/build
.PHONY : simple-2d-constraint-solver/fast

#=============================================================================
# Target rules for targets named simple-2d-constraint-solver-test

# Build rule for target.
simple-2d-constraint-solver-test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simple-2d-constraint-solver-test
.PHONY : simple-2d-constraint-solver-test

# fast build rule for target.
simple-2d-constraint-solver-test/fast:
	$(MAKE) $(MAKESILENT) -f engine-sim/dependencies/submodules/simple-2d-constraint-solver/CMakeFiles/simple-2d-constraint-solver-test.dir/build.make engine-sim/dependencies/submodules/simple-2d-constraint-solver/CMakeFiles/simple-2d-constraint-solver-test.dir/build
.PHONY : simple-2d-constraint-solver-test/fast

#=============================================================================
# Target rules for targets named csv-io

# Build rule for target.
csv-io: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 csv-io
.PHONY : csv-io

# fast build rule for target.
csv-io/fast:
	$(MAKE) $(MAKESILENT) -f engine-sim/dependencies/submodules/csv-io/CMakeFiles/csv-io.dir/build.make engine-sim/dependencies/submodules/csv-io/CMakeFiles/csv-io.dir/build
.PHONY : csv-io/fast

#=============================================================================
# Target rules for targets named csv-io-main

# Build rule for target.
csv-io-main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 csv-io-main
.PHONY : csv-io-main

# fast build rule for target.
csv-io-main/fast:
	$(MAKE) $(MAKESILENT) -f engine-sim/dependencies/submodules/csv-io/CMakeFiles/csv-io-main.dir/build.make engine-sim/dependencies/submodules/csv-io/CMakeFiles/csv-io-main.dir/build
.PHONY : csv-io-main/fast

#=============================================================================
# Target rules for targets named csv-io-test

# Build rule for target.
csv-io-test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 csv-io-test
.PHONY : csv-io-test

# fast build rule for target.
csv-io-test/fast:
	$(MAKE) $(MAKESILENT) -f engine-sim/dependencies/submodules/csv-io/CMakeFiles/csv-io-test.dir/build.make engine-sim/dependencies/submodules/csv-io/CMakeFiles/csv-io-test.dir/build
.PHONY : csv-io-test/fast

#=============================================================================
# Target rules for targets named piranha

# Build rule for target.
piranha: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 piranha
.PHONY : piranha

# fast build rule for target.
piranha/fast:
	$(MAKE) $(MAKESILENT) -f engine-sim/dependencies/submodules/piranha/CMakeFiles/piranha.dir/build.make engine-sim/dependencies/submodules/piranha/CMakeFiles/piranha.dir/build
.PHONY : piranha/fast

#=============================================================================
# Target rules for targets named piranha_reference_compiler

# Build rule for target.
piranha_reference_compiler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 piranha_reference_compiler
.PHONY : piranha_reference_compiler

# fast build rule for target.
piranha_reference_compiler/fast:
	$(MAKE) $(MAKESILENT) -f engine-sim/dependencies/submodules/piranha/CMakeFiles/piranha_reference_compiler.dir/build.make engine-sim/dependencies/submodules/piranha/CMakeFiles/piranha_reference_compiler.dir/build
.PHONY : piranha_reference_compiler/fast

#=============================================================================
# Target rules for targets named piranha_test

# Build rule for target.
piranha_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 piranha_test
.PHONY : piranha_test

# fast build rule for target.
piranha_test/fast:
	$(MAKE) $(MAKESILENT) -f engine-sim/dependencies/submodules/piranha/CMakeFiles/piranha_test.dir/build.make engine-sim/dependencies/submodules/piranha/CMakeFiles/piranha_test.dir/build
.PHONY : piranha_test/fast

#=============================================================================
# Target rules for targets named smoke_tests

# Build rule for target.
smoke_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 smoke_tests
.PHONY : smoke_tests

# fast build rule for target.
smoke_tests/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/smoke_tests.dir/build.make test/CMakeFiles/smoke_tests.dir/build
.PHONY : smoke_tests/fast

#=============================================================================
# Target rules for targets named integration_tests

# Build rule for target.
integration_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 integration_tests
.PHONY : integration_tests

# fast build rule for target.
integration_tests/fast:
	$(MAKE) $(MAKESILENT) -f test/integration/CMakeFiles/integration_tests.dir/build.make test/integration/CMakeFiles/integration_tests.dir/build
.PHONY : integration_tests/fast

#=============================================================================
# Target rules for targets named unit_tests

# Build rule for target.
unit_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit_tests
.PHONY : unit_tests

# fast build rule for target.
unit_tests/fast:
	$(MAKE) $(MAKESILENT) -f test/unit/CMakeFiles/unit_tests.dir/build.make test/unit/CMakeFiles/unit_tests.dir/build
.PHONY : unit_tests/fast

src/AudioPlayer.o: src/AudioPlayer.cpp.o
.PHONY : src/AudioPlayer.o

# target to build an object file
src/AudioPlayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/AudioPlayer.cpp.o
.PHONY : src/AudioPlayer.cpp.o

src/AudioPlayer.i: src/AudioPlayer.cpp.i
.PHONY : src/AudioPlayer.i

# target to preprocess a source file
src/AudioPlayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/AudioPlayer.cpp.i
.PHONY : src/AudioPlayer.cpp.i

src/AudioPlayer.s: src/AudioPlayer.cpp.s
.PHONY : src/AudioPlayer.s

# target to generate assembly for a file
src/AudioPlayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/AudioPlayer.cpp.s
.PHONY : src/AudioPlayer.cpp.s

src/AudioSource.o: src/AudioSource.cpp.o
.PHONY : src/AudioSource.o

# target to build an object file
src/AudioSource.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/AudioSource.cpp.o
.PHONY : src/AudioSource.cpp.o

src/AudioSource.i: src/AudioSource.cpp.i
.PHONY : src/AudioSource.i

# target to preprocess a source file
src/AudioSource.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/AudioSource.cpp.i
.PHONY : src/AudioSource.cpp.i

src/AudioSource.s: src/AudioSource.cpp.s
.PHONY : src/AudioSource.s

# target to generate assembly for a file
src/AudioSource.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/AudioSource.cpp.s
.PHONY : src/AudioSource.cpp.s

src/SyncPullAudio.o: src/SyncPullAudio.cpp.o
.PHONY : src/SyncPullAudio.o

# target to build an object file
src/SyncPullAudio.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/SyncPullAudio.cpp.o
.PHONY : src/SyncPullAudio.cpp.o

src/SyncPullAudio.i: src/SyncPullAudio.cpp.i
.PHONY : src/SyncPullAudio.i

# target to preprocess a source file
src/SyncPullAudio.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/SyncPullAudio.cpp.i
.PHONY : src/SyncPullAudio.cpp.i

src/SyncPullAudio.s: src/SyncPullAudio.cpp.s
.PHONY : src/SyncPullAudio.s

# target to generate assembly for a file
src/SyncPullAudio.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/SyncPullAudio.cpp.s
.PHONY : src/SyncPullAudio.cpp.s

src/audio/common/BridgeAudioSource.o: src/audio/common/BridgeAudioSource.cpp.o
.PHONY : src/audio/common/BridgeAudioSource.o

# target to build an object file
src/audio/common/BridgeAudioSource.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/audio/common/BridgeAudioSource.cpp.o
.PHONY : src/audio/common/BridgeAudioSource.cpp.o

src/audio/common/BridgeAudioSource.i: src/audio/common/BridgeAudioSource.cpp.i
.PHONY : src/audio/common/BridgeAudioSource.i

# target to preprocess a source file
src/audio/common/BridgeAudioSource.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/audio/common/BridgeAudioSource.cpp.i
.PHONY : src/audio/common/BridgeAudioSource.cpp.i

src/audio/common/BridgeAudioSource.s: src/audio/common/BridgeAudioSource.cpp.s
.PHONY : src/audio/common/BridgeAudioSource.s

# target to generate assembly for a file
src/audio/common/BridgeAudioSource.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/audio/common/BridgeAudioSource.cpp.s
.PHONY : src/audio/common/BridgeAudioSource.cpp.s

src/audio/common/CircularBuffer.o: src/audio/common/CircularBuffer.cpp.o
.PHONY : src/audio/common/CircularBuffer.o

# target to build an object file
src/audio/common/CircularBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/audio/common/CircularBuffer.cpp.o
.PHONY : src/audio/common/CircularBuffer.cpp.o

src/audio/common/CircularBuffer.i: src/audio/common/CircularBuffer.cpp.i
.PHONY : src/audio/common/CircularBuffer.i

# target to preprocess a source file
src/audio/common/CircularBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/audio/common/CircularBuffer.cpp.i
.PHONY : src/audio/common/CircularBuffer.cpp.i

src/audio/common/CircularBuffer.s: src/audio/common/CircularBuffer.cpp.s
.PHONY : src/audio/common/CircularBuffer.s

# target to generate assembly for a file
src/audio/common/CircularBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/audio/common/CircularBuffer.cpp.s
.PHONY : src/audio/common/CircularBuffer.cpp.s

src/audio/platform/macos/CoreAudioPlatform.o: src/audio/platform/macos/CoreAudioPlatform.cpp.o
.PHONY : src/audio/platform/macos/CoreAudioPlatform.o

# target to build an object file
src/audio/platform/macos/CoreAudioPlatform.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/audio/platform/macos/CoreAudioPlatform.cpp.o
.PHONY : src/audio/platform/macos/CoreAudioPlatform.cpp.o

src/audio/platform/macos/CoreAudioPlatform.i: src/audio/platform/macos/CoreAudioPlatform.cpp.i
.PHONY : src/audio/platform/macos/CoreAudioPlatform.i

# target to preprocess a source file
src/audio/platform/macos/CoreAudioPlatform.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/audio/platform/macos/CoreAudioPlatform.cpp.i
.PHONY : src/audio/platform/macos/CoreAudioPlatform.cpp.i

src/audio/platform/macos/CoreAudioPlatform.s: src/audio/platform/macos/CoreAudioPlatform.cpp.s
.PHONY : src/audio/platform/macos/CoreAudioPlatform.s

# target to generate assembly for a file
src/audio/platform/macos/CoreAudioPlatform.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/audio/platform/macos/CoreAudioPlatform.cpp.s
.PHONY : src/audio/platform/macos/CoreAudioPlatform.cpp.s

src/audio/renderers/AudioRendererFactory.o: src/audio/renderers/AudioRendererFactory.cpp.o
.PHONY : src/audio/renderers/AudioRendererFactory.o

# target to build an object file
src/audio/renderers/AudioRendererFactory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/audio/renderers/AudioRendererFactory.cpp.o
.PHONY : src/audio/renderers/AudioRendererFactory.cpp.o

src/audio/renderers/AudioRendererFactory.i: src/audio/renderers/AudioRendererFactory.cpp.i
.PHONY : src/audio/renderers/AudioRendererFactory.i

# target to preprocess a source file
src/audio/renderers/AudioRendererFactory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/audio/renderers/AudioRendererFactory.cpp.i
.PHONY : src/audio/renderers/AudioRendererFactory.cpp.i

src/audio/renderers/AudioRendererFactory.s: src/audio/renderers/AudioRendererFactory.cpp.s
.PHONY : src/audio/renderers/AudioRendererFactory.s

# target to generate assembly for a file
src/audio/renderers/AudioRendererFactory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/audio/renderers/AudioRendererFactory.cpp.s
.PHONY : src/audio/renderers/AudioRendererFactory.cpp.s

src/audio/renderers/SyncPullRenderer.o: src/audio/renderers/SyncPullRenderer.cpp.o
.PHONY : src/audio/renderers/SyncPullRenderer.o

# target to build an object file
src/audio/renderers/SyncPullRenderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/audio/renderers/SyncPullRenderer.cpp.o
.PHONY : src/audio/renderers/SyncPullRenderer.cpp.o

src/audio/renderers/SyncPullRenderer.i: src/audio/renderers/SyncPullRenderer.cpp.i
.PHONY : src/audio/renderers/SyncPullRenderer.i

# target to preprocess a source file
src/audio/renderers/SyncPullRenderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/audio/renderers/SyncPullRenderer.cpp.i
.PHONY : src/audio/renderers/SyncPullRenderer.cpp.i

src/audio/renderers/SyncPullRenderer.s: src/audio/renderers/SyncPullRenderer.cpp.s
.PHONY : src/audio/renderers/SyncPullRenderer.s

# target to generate assembly for a file
src/audio/renderers/SyncPullRenderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/audio/renderers/SyncPullRenderer.cpp.s
.PHONY : src/audio/renderers/SyncPullRenderer.cpp.s

src/audio/renderers/ThreadedRenderer.o: src/audio/renderers/ThreadedRenderer.cpp.o
.PHONY : src/audio/renderers/ThreadedRenderer.o

# target to build an object file
src/audio/renderers/ThreadedRenderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/audio/renderers/ThreadedRenderer.cpp.o
.PHONY : src/audio/renderers/ThreadedRenderer.cpp.o

src/audio/renderers/ThreadedRenderer.i: src/audio/renderers/ThreadedRenderer.cpp.i
.PHONY : src/audio/renderers/ThreadedRenderer.i

# target to preprocess a source file
src/audio/renderers/ThreadedRenderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/audio/renderers/ThreadedRenderer.cpp.i
.PHONY : src/audio/renderers/ThreadedRenderer.cpp.i

src/audio/renderers/ThreadedRenderer.s: src/audio/renderers/ThreadedRenderer.cpp.s
.PHONY : src/audio/renderers/ThreadedRenderer.s

# target to generate assembly for a file
src/audio/renderers/ThreadedRenderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/audio/renderers/ThreadedRenderer.cpp.s
.PHONY : src/audio/renderers/ThreadedRenderer.cpp.s

src/audio/strategies/IAudioStrategyFactory.o: src/audio/strategies/IAudioStrategyFactory.cpp.o
.PHONY : src/audio/strategies/IAudioStrategyFactory.o

# target to build an object file
src/audio/strategies/IAudioStrategyFactory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/audio/strategies/IAudioStrategyFactory.cpp.o
.PHONY : src/audio/strategies/IAudioStrategyFactory.cpp.o

src/audio/strategies/IAudioStrategyFactory.i: src/audio/strategies/IAudioStrategyFactory.cpp.i
.PHONY : src/audio/strategies/IAudioStrategyFactory.i

# target to preprocess a source file
src/audio/strategies/IAudioStrategyFactory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/audio/strategies/IAudioStrategyFactory.cpp.i
.PHONY : src/audio/strategies/IAudioStrategyFactory.cpp.i

src/audio/strategies/IAudioStrategyFactory.s: src/audio/strategies/IAudioStrategyFactory.cpp.s
.PHONY : src/audio/strategies/IAudioStrategyFactory.s

# target to generate assembly for a file
src/audio/strategies/IAudioStrategyFactory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/audio/strategies/IAudioStrategyFactory.cpp.s
.PHONY : src/audio/strategies/IAudioStrategyFactory.cpp.s

src/audio/strategies/SyncPullStrategy.o: src/audio/strategies/SyncPullStrategy.cpp.o
.PHONY : src/audio/strategies/SyncPullStrategy.o

# target to build an object file
src/audio/strategies/SyncPullStrategy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/audio/strategies/SyncPullStrategy.cpp.o
.PHONY : src/audio/strategies/SyncPullStrategy.cpp.o

src/audio/strategies/SyncPullStrategy.i: src/audio/strategies/SyncPullStrategy.cpp.i
.PHONY : src/audio/strategies/SyncPullStrategy.i

# target to preprocess a source file
src/audio/strategies/SyncPullStrategy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/audio/strategies/SyncPullStrategy.cpp.i
.PHONY : src/audio/strategies/SyncPullStrategy.cpp.i

src/audio/strategies/SyncPullStrategy.s: src/audio/strategies/SyncPullStrategy.cpp.s
.PHONY : src/audio/strategies/SyncPullStrategy.s

# target to generate assembly for a file
src/audio/strategies/SyncPullStrategy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/audio/strategies/SyncPullStrategy.cpp.s
.PHONY : src/audio/strategies/SyncPullStrategy.cpp.s

src/audio/strategies/ThreadedStrategy.o: src/audio/strategies/ThreadedStrategy.cpp.o
.PHONY : src/audio/strategies/ThreadedStrategy.o

# target to build an object file
src/audio/strategies/ThreadedStrategy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/audio/strategies/ThreadedStrategy.cpp.o
.PHONY : src/audio/strategies/ThreadedStrategy.cpp.o

src/audio/strategies/ThreadedStrategy.i: src/audio/strategies/ThreadedStrategy.cpp.i
.PHONY : src/audio/strategies/ThreadedStrategy.i

# target to preprocess a source file
src/audio/strategies/ThreadedStrategy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/audio/strategies/ThreadedStrategy.cpp.i
.PHONY : src/audio/strategies/ThreadedStrategy.cpp.i

src/audio/strategies/ThreadedStrategy.s: src/audio/strategies/ThreadedStrategy.cpp.s
.PHONY : src/audio/strategies/ThreadedStrategy.s

# target to generate assembly for a file
src/audio/strategies/ThreadedStrategy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/audio/strategies/ThreadedStrategy.cpp.s
.PHONY : src/audio/strategies/ThreadedStrategy.cpp.s

src/config/ANSIColors.o: src/config/ANSIColors.cpp.o
.PHONY : src/config/ANSIColors.o

# target to build an object file
src/config/ANSIColors.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/config/ANSIColors.cpp.o
.PHONY : src/config/ANSIColors.cpp.o

src/config/ANSIColors.i: src/config/ANSIColors.cpp.i
.PHONY : src/config/ANSIColors.i

# target to preprocess a source file
src/config/ANSIColors.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/config/ANSIColors.cpp.i
.PHONY : src/config/ANSIColors.cpp.i

src/config/ANSIColors.s: src/config/ANSIColors.cpp.s
.PHONY : src/config/ANSIColors.s

# target to generate assembly for a file
src/config/ANSIColors.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/config/ANSIColors.cpp.s
.PHONY : src/config/ANSIColors.cpp.s

src/config/CLIMain.o: src/config/CLIMain.cpp.o
.PHONY : src/config/CLIMain.o

# target to build an object file
src/config/CLIMain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/config/CLIMain.cpp.o
.PHONY : src/config/CLIMain.cpp.o

src/config/CLIMain.i: src/config/CLIMain.cpp.i
.PHONY : src/config/CLIMain.i

# target to preprocess a source file
src/config/CLIMain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/config/CLIMain.cpp.i
.PHONY : src/config/CLIMain.cpp.i

src/config/CLIMain.s: src/config/CLIMain.cpp.s
.PHONY : src/config/CLIMain.s

# target to generate assembly for a file
src/config/CLIMain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/config/CLIMain.cpp.s
.PHONY : src/config/CLIMain.cpp.s

src/config/CLIconfig.o: src/config/CLIconfig.cpp.o
.PHONY : src/config/CLIconfig.o

# target to build an object file
src/config/CLIconfig.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/config/CLIconfig.cpp.o
.PHONY : src/config/CLIconfig.cpp.o

src/config/CLIconfig.i: src/config/CLIconfig.cpp.i
.PHONY : src/config/CLIconfig.i

# target to preprocess a source file
src/config/CLIconfig.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/config/CLIconfig.cpp.i
.PHONY : src/config/CLIconfig.cpp.i

src/config/CLIconfig.s: src/config/CLIconfig.cpp.s
.PHONY : src/config/CLIconfig.s

# target to generate assembly for a file
src/config/CLIconfig.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/config/CLIconfig.cpp.s
.PHONY : src/config/CLIconfig.cpp.s

src/input/KeyboardInput.o: src/input/KeyboardInput.cpp.o
.PHONY : src/input/KeyboardInput.o

# target to build an object file
src/input/KeyboardInput.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/input/KeyboardInput.cpp.o
.PHONY : src/input/KeyboardInput.cpp.o

src/input/KeyboardInput.i: src/input/KeyboardInput.cpp.i
.PHONY : src/input/KeyboardInput.i

# target to preprocess a source file
src/input/KeyboardInput.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/input/KeyboardInput.cpp.i
.PHONY : src/input/KeyboardInput.cpp.i

src/input/KeyboardInput.s: src/input/KeyboardInput.cpp.s
.PHONY : src/input/KeyboardInput.s

# target to generate assembly for a file
src/input/KeyboardInput.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/input/KeyboardInput.cpp.s
.PHONY : src/input/KeyboardInput.cpp.s

src/input/KeyboardInputProvider.o: src/input/KeyboardInputProvider.cpp.o
.PHONY : src/input/KeyboardInputProvider.o

# target to build an object file
src/input/KeyboardInputProvider.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/input/KeyboardInputProvider.cpp.o
.PHONY : src/input/KeyboardInputProvider.cpp.o

src/input/KeyboardInputProvider.i: src/input/KeyboardInputProvider.cpp.i
.PHONY : src/input/KeyboardInputProvider.i

# target to preprocess a source file
src/input/KeyboardInputProvider.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/input/KeyboardInputProvider.cpp.i
.PHONY : src/input/KeyboardInputProvider.cpp.i

src/input/KeyboardInputProvider.s: src/input/KeyboardInputProvider.cpp.s
.PHONY : src/input/KeyboardInputProvider.s

# target to generate assembly for a file
src/input/KeyboardInputProvider.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/input/KeyboardInputProvider.cpp.s
.PHONY : src/input/KeyboardInputProvider.cpp.s

src/presentation/ConsolePresentation.o: src/presentation/ConsolePresentation.cpp.o
.PHONY : src/presentation/ConsolePresentation.o

# target to build an object file
src/presentation/ConsolePresentation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/presentation/ConsolePresentation.cpp.o
.PHONY : src/presentation/ConsolePresentation.cpp.o

src/presentation/ConsolePresentation.i: src/presentation/ConsolePresentation.cpp.i
.PHONY : src/presentation/ConsolePresentation.i

# target to preprocess a source file
src/presentation/ConsolePresentation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/presentation/ConsolePresentation.cpp.i
.PHONY : src/presentation/ConsolePresentation.cpp.i

src/presentation/ConsolePresentation.s: src/presentation/ConsolePresentation.cpp.s
.PHONY : src/presentation/ConsolePresentation.s

# target to generate assembly for a file
src/presentation/ConsolePresentation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/presentation/ConsolePresentation.cpp.s
.PHONY : src/presentation/ConsolePresentation.cpp.s

src/simulation/EngineConfig.o: src/simulation/EngineConfig.cpp.o
.PHONY : src/simulation/EngineConfig.o

# target to build an object file
src/simulation/EngineConfig.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/simulation/EngineConfig.cpp.o
.PHONY : src/simulation/EngineConfig.cpp.o

src/simulation/EngineConfig.i: src/simulation/EngineConfig.cpp.i
.PHONY : src/simulation/EngineConfig.i

# target to preprocess a source file
src/simulation/EngineConfig.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/simulation/EngineConfig.cpp.i
.PHONY : src/simulation/EngineConfig.cpp.i

src/simulation/EngineConfig.s: src/simulation/EngineConfig.cpp.s
.PHONY : src/simulation/EngineConfig.s

# target to generate assembly for a file
src/simulation/EngineConfig.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/simulation/EngineConfig.cpp.s
.PHONY : src/simulation/EngineConfig.cpp.s

src/simulation/SimulationLoop.o: src/simulation/SimulationLoop.cpp.o
.PHONY : src/simulation/SimulationLoop.o

# target to build an object file
src/simulation/SimulationLoop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/simulation/SimulationLoop.cpp.o
.PHONY : src/simulation/SimulationLoop.cpp.o

src/simulation/SimulationLoop.i: src/simulation/SimulationLoop.cpp.i
.PHONY : src/simulation/SimulationLoop.i

# target to preprocess a source file
src/simulation/SimulationLoop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/simulation/SimulationLoop.cpp.i
.PHONY : src/simulation/SimulationLoop.cpp.i

src/simulation/SimulationLoop.s: src/simulation/SimulationLoop.cpp.s
.PHONY : src/simulation/SimulationLoop.s

# target to generate assembly for a file
src/simulation/SimulationLoop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/engine-sim-cli.dir/build.make CMakeFiles/engine-sim-cli.dir/src/simulation/SimulationLoop.cpp.s
.PHONY : src/simulation/SimulationLoop.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... copy-engine-sim-bridge"
	@echo "... run_tests"
	@echo "... bridge_unit_tests"
	@echo "... csv-io"
	@echo "... csv-io-main"
	@echo "... csv-io-test"
	@echo "... engine-sim"
	@echo "... engine-sim-app"
	@echo "... engine-sim-bridge"
	@echo "... engine-sim-cli"
	@echo "... engine-sim-script-interpreter"
	@echo "... engine-sim-test"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... integration_tests"
	@echo "... piranha"
	@echo "... piranha_reference_compiler"
	@echo "... piranha_test"
	@echo "... simple-2d-constraint-solver"
	@echo "... simple-2d-constraint-solver-test"
	@echo "... smoke_tests"
	@echo "... unit_tests"
	@echo "... src/AudioPlayer.o"
	@echo "... src/AudioPlayer.i"
	@echo "... src/AudioPlayer.s"
	@echo "... src/AudioSource.o"
	@echo "... src/AudioSource.i"
	@echo "... src/AudioSource.s"
	@echo "... src/SyncPullAudio.o"
	@echo "... src/SyncPullAudio.i"
	@echo "... src/SyncPullAudio.s"
	@echo "... src/audio/common/BridgeAudioSource.o"
	@echo "... src/audio/common/BridgeAudioSource.i"
	@echo "... src/audio/common/BridgeAudioSource.s"
	@echo "... src/audio/common/CircularBuffer.o"
	@echo "... src/audio/common/CircularBuffer.i"
	@echo "... src/audio/common/CircularBuffer.s"
	@echo "... src/audio/platform/macos/CoreAudioPlatform.o"
	@echo "... src/audio/platform/macos/CoreAudioPlatform.i"
	@echo "... src/audio/platform/macos/CoreAudioPlatform.s"
	@echo "... src/audio/renderers/AudioRendererFactory.o"
	@echo "... src/audio/renderers/AudioRendererFactory.i"
	@echo "... src/audio/renderers/AudioRendererFactory.s"
	@echo "... src/audio/renderers/SyncPullRenderer.o"
	@echo "... src/audio/renderers/SyncPullRenderer.i"
	@echo "... src/audio/renderers/SyncPullRenderer.s"
	@echo "... src/audio/renderers/ThreadedRenderer.o"
	@echo "... src/audio/renderers/ThreadedRenderer.i"
	@echo "... src/audio/renderers/ThreadedRenderer.s"
	@echo "... src/audio/strategies/IAudioStrategyFactory.o"
	@echo "... src/audio/strategies/IAudioStrategyFactory.i"
	@echo "... src/audio/strategies/IAudioStrategyFactory.s"
	@echo "... src/audio/strategies/SyncPullStrategy.o"
	@echo "... src/audio/strategies/SyncPullStrategy.i"
	@echo "... src/audio/strategies/SyncPullStrategy.s"
	@echo "... src/audio/strategies/ThreadedStrategy.o"
	@echo "... src/audio/strategies/ThreadedStrategy.i"
	@echo "... src/audio/strategies/ThreadedStrategy.s"
	@echo "... src/config/ANSIColors.o"
	@echo "... src/config/ANSIColors.i"
	@echo "... src/config/ANSIColors.s"
	@echo "... src/config/CLIMain.o"
	@echo "... src/config/CLIMain.i"
	@echo "... src/config/CLIMain.s"
	@echo "... src/config/CLIconfig.o"
	@echo "... src/config/CLIconfig.i"
	@echo "... src/config/CLIconfig.s"
	@echo "... src/input/KeyboardInput.o"
	@echo "... src/input/KeyboardInput.i"
	@echo "... src/input/KeyboardInput.s"
	@echo "... src/input/KeyboardInputProvider.o"
	@echo "... src/input/KeyboardInputProvider.i"
	@echo "... src/input/KeyboardInputProvider.s"
	@echo "... src/presentation/ConsolePresentation.o"
	@echo "... src/presentation/ConsolePresentation.i"
	@echo "... src/presentation/ConsolePresentation.s"
	@echo "... src/simulation/EngineConfig.o"
	@echo "... src/simulation/EngineConfig.i"
	@echo "... src/simulation/EngineConfig.s"
	@echo "... src/simulation/SimulationLoop.o"
	@echo "... src/simulation/SimulationLoop.i"
	@echo "... src/simulation/SimulationLoop.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

