// AUTO-GENERATED by scripts/ota-generate-keys.sh — DO NOT COMMIT.
//
// Per-user ed25519ph OTA signing public key (raw 32 bytes, RFC 8032 Ed25519ph).
// Regenerated from YOUR private key by:  make ota-keys
// The matching private key lives ONLY on your host
// (/Users/danielsinclair/.vehicle-sim/ota/ed25519.pem), never in this repo.
#ifndef OTA_PUBLIC_KEY_H
#define OTA_PUBLIC_KEY_H

#include <stdint.h>

// Raw ed25519 public key (32 bytes). Verify side only.
static const uint8_t OTA_PUBLIC_KEY[32] = {
    0x73, 0x38, 0x39, 0xbc, 0x5d, 0x9f, 0xc7, 0x89,
    0x49, 0x0e, 0x3a, 0xbe, 0x2e, 0x36, 0x51, 0x0c,
    0x69, 0x84, 0x54, 0x04, 0x28, 0x7d, 0xae, 0x9a,
    0xc1, 0x06, 0xd9, 0x88, 0x47, 0xe0, 0xfd, 0x6d,
};

#endif  // OTA_PUBLIC_KEY_H
