#!/usr/bin/env bash
# ota-generate-keys.sh — generate a per-user ed25519 OTA signing keypair.
#
#   Private key  -> ~/.vehicle-sim/ota/ed25519.pem   (NEVER committed)
#   Public key   -> firmware/can-bridge/OtaPublicKey.h (baked into the firmware,
#                    gitignored — regenerated from your private key each run)
#
# The private key is yours alone. Each device you flash trusts YOUR public key.
# To let another user/device accept images, they bake THEIR public key.
#
# Usage:
#   scripts/ota-generate-keys.sh              # create if missing (idempotent)
#   scripts/ota-generate-keys.sh --force      # overwrite an existing keypair
#   scripts/ota-generate-keys.sh --keys-dir DIR
#   scripts/ota-generate-keys.sh --header firmware/can-bridge/OtaPublicKey.h
#
# Requires: openssl 3.x  ( brew install openssl || it's stock on macOS )
set -euo pipefail

# ── Defaults ────────────────────────────────────────────────────────────
KEYS_DIR="${HOME}/.vehicle-sim/ota"
PRIV_KEY="${KEYS_DIR}/ed25519.pem"
PUB_KEY="${KEYS_DIR}/ed25519_pub.pem"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HEADER="${REPO_ROOT}/firmware/can-bridge/OtaPublicKey.h"
FORCE=0

# ── Args ────────────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case "$1" in
        --force|-f)        FORCE=1; shift ;;
        --keys-dir)        KEYS_DIR="$2"; PRIV_KEY="${KEYS_DIR}/ed25519.pem"; PUB_KEY="${KEYS_DIR}/ed25519_pub.pem"; shift 2 ;;
        --header)          HEADER="$2"; shift 2 ;;
        --help|-h)
            sed -n '2,18p' "$0"; exit 0 ;;
        *) echo "Unknown arg: $1" >&2; exit 2 ;;
    esac
done

# ── Checks ──────────────────────────────────────────────────────────────
command -v openssl >/dev/null 2>&1 || { echo "Error: openssl not found." >&2; exit 1; }
[[ -d "${REPO_ROOT}/firmware/can-bridge" ]] || { echo "Error: run from repo root; firmware/can-bridge missing." >&2; exit 1; }

# ── Generate keypair (idempotent) ───────────────────────────────────────
mkdir -p "${KEYS_DIR}"
chmod 700 "${KEYS_DIR}"

if [[ -f "${PRIV_KEY}" && "${FORCE}" -eq 0 ]]; then
    echo "Private key exists: ${PRIV_KEY}  (use --force to regenerate)"
else
    if [[ -f "${PRIV_KEY}" ]]; then
        echo "Overwriting existing keypair (--force)"
        rm -f "${PRIV_KEY}" "${PUB_KEY}"
    fi
    openssl genpkey -algorithm ed25519 -out "${PRIV_KEY}" 2>/dev/null
    chmod 600 "${PRIV_KEY}"
    echo "Generated private key: ${PRIV_KEY}"
fi

# Always (re)derive the public key from the private key — cheap and correct.
openssl pkey -in "${PRIV_KEY}" -pubout -out "${PUB_KEY}" 2>/dev/null
echo "Public key:            ${PUB_KEY}"

# ── Extract raw 32-byte public key & emit the header ────────────────────
# ed25519 SubjectPublicKeyInfo DER = 12-byte ASN.1 header + 32 raw bytes.
DER="$(openssl pkey -in "${PUB_KEY}" -pubin -outform DER 2>/dev/null | tail -c 32 | xxd -p -c 64)"
[[ ${#DER} -eq 64 ]] || { echo "Error: derived public key is not 32 bytes (got ${#DER} hex chars)." >&2; exit 1; }

# Format as 0xNN, 8 per row.
HEX_PAIRS=()
for (( i=0; i<64; i+=2 )); do
    HEX_PAIRS+=( "0x${DER:$i:2}" )
done

{
    echo "// AUTO-GENERATED by scripts/ota-generate-keys.sh — DO NOT COMMIT."
    echo "//"
    echo "// Per-user ed25519ph OTA signing public key (raw 32 bytes, RFC 8032 Ed25519ph)."
    echo "// Regenerated from YOUR private key by:  make ota-keys"
    echo "// The matching private key lives ONLY on your host"
    echo "// (${PRIV_KEY}), never in this repo."
    echo "#ifndef OTA_PUBLIC_KEY_H"
    echo "#define OTA_PUBLIC_KEY_H"
    echo ""
    echo "#include <stdint.h>"
    echo ""
    echo "// Raw ed25519 public key (32 bytes). Verify side only."
    echo "static const uint8_t OTA_PUBLIC_KEY[32] = {"
    for (( row=0; row<4; row++ )); do
        printf "    %s, %s, %s, %s, %s, %s, %s, %s,\n" \
            "${HEX_PAIRS[$((row*8+0))]}" "${HEX_PAIRS[$((row*8+1))]}" \
            "${HEX_PAIRS[$((row*8+2))]}" "${HEX_PAIRS[$((row*8+3))]}" \
            "${HEX_PAIRS[$((row*8+4))]}" "${HEX_PAIRS[$((row*8+5))]}" \
            "${HEX_PAIRS[$((row*8+6))]}" "${HEX_PAIRS[$((row*8+7))]}"
    done
    echo "};"
    echo ""
    echo "#endif  // OTA_PUBLIC_KEY_H"
} > "${HEADER}"

echo "Baked public key ->    ${HEADER}"
echo "Done. Flash the firmware (make flash) to install this key on a device."
