#!/usr/bin/env python3
"""Tests for the update-dbc guard — `make update-dbc` must be opt-in.

resources/dbc/Model3CAN.dbc is the aggregate DBC generated by
scripts/gen_aggregate_dbc.py (alias/rename policy in dbc/aliases.toml) and
carries consumer-facing signal names (DI_gear, VCLEFT_brakeLightStatus, ...)
that the raw opendbc tesla_model3_party.dbc does not provide verbatim. The
unguarded update-dbc recipe copied the raw opendbc file over it, silently
destroying the aggregate on a plain `make update-dbc`.

Contract under test:

  * Without FORCE, `make update-dbc` refuses: non-zero exit, an explanation
    naming the opt-in, and NOTHING touched (no DBC modified, no backup or
    temp file left behind in resources/dbc/).
  * The destructive commands (git checkout/pull, cp from external/opendbc)
    appear in the recipe ONLY under FORCE=1.

The destructive branch is verified exclusively via `make -n` (dry run): make
prints the recipe it would run without executing it, so FORCE=1 is never
actually run by this suite.

Run:  python3 test/scripts/test_update_dbc_guard.py
"""

import hashlib
import subprocess
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DBC_DIR = REPO_ROOT / "resources" / "dbc"
GUARDED_DBCS = ["Model3CAN.dbc", "vw_mlb.dbc"]
DESTRUCTIVE_MARKERS = (
    "git checkout master",
    "git pull",
    "cp external/opendbc",
)


def _make(args, timeout=120):
    return subprocess.run(
        ["make", *args],
        cwd=REPO_ROOT,
        text=True,
        capture_output=True,
        timeout=timeout,
    )


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


class UpdateDbcGuardTest(unittest.TestCase):
    def test_no_force_dry_run_has_no_destructive_commands(self):
        """Without FORCE the recipe make WOULD run contains nothing destructive."""
        result = _make(["-n", "update-dbc"])
        self.assertEqual(result.returncode, 0, result.stderr)
        for marker in DESTRUCTIVE_MARKERS:
            self.assertNotIn(
                marker,
                result.stdout,
                f"unguarded `make update-dbc` would run: {marker}",
            )

    def test_no_force_run_aborts_without_touching_dbcs(self):
        """A real `make update-dbc` (no FORCE) must abort and change nothing."""
        before = {p.name: _sha256(p) for p in sorted(DBC_DIR.iterdir())}

        result = _make(["update-dbc"])

        self.assertNotEqual(result.returncode, 0, "guard must exit non-zero")
        combined = result.stdout + result.stderr
        self.assertIn("FORCE=1", combined, "refusal must name the opt-in")
        for name in GUARDED_DBCS:
            self.assertIn(name, before)
            self.assertEqual(
                _sha256(DBC_DIR / name),
                before[name],
                f"{name} must be byte-identical after a refused update-dbc",
            )
        after = {p.name: _sha256(p) for p in sorted(DBC_DIR.iterdir())}
        self.assertEqual(
            after,
            before,
            "refused update-dbc must not modify, create, or delete anything "
            "in resources/dbc/ (including backup/temp files)",
        )

    def test_force_dry_run_unlocks_destructive_recipe(self):
        """With FORCE=1 the real recipe is selected (dry run only — never executed)."""
        result = _make(["-n", "update-dbc", "FORCE=1"])
        self.assertEqual(result.returncode, 0, result.stderr)
        for marker in DESTRUCTIVE_MARKERS:
            self.assertIn(
                marker,
                result.stdout,
                f"FORCE=1 must unlock the real recipe (expected: {marker})",
            )


if __name__ == "__main__":
    unittest.main()
